baseurl = "https://anirbaaaan183.github.io/blog/"
theme = "hugo-theme-stack"
title = "anirbaaaan183's blog"
copyright = "anirbaaaan183"
hasCJKLanguage = false

[services.disqus]
shortname = "hugo-theme-stack"

[services.googleAnalytics]

[pagination]
pagerSize = 3

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]
  since = 2_024

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  emoji = "🍥"
  subtitle = "Hi! I am anirbaaaan. This is my blog for posting my thoughts, acheivements and shitposts. More details in About!"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

  [params.article]
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = true
    default = "Licensed under the MIT License"

  [params.comments]
  enabled = true
  provider = "giscus"

    [params.comments.giscus]
    repo = "anirbaaaan183/blog"
    repoID = "R_kgDONdMlFw"
    category = "comments"
    categoryID = "DIC_kwDONdMlF84ClOW6"
    mapping = "pathname"
    strict = 1
    lightTheme = "light"
    darkTheme = "dark_dimmed"
    reactionsEnabled = 1
    emitMetadata = 0
    inputPosition = "top"
    lang = "en"


[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

  [params.widgets.homepage.params]
  limit = 5

[[params.widgets.homepage]]
type = "categories"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.page]]
type = "toc"

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
main = [ ]

  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/anirbaaaan183/"

    [menu.social.params]
    icon = "brand-github"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.extensions.passthrough]
enable = true

  [markup.goldmark.extensions.passthrough.delimiters]
  block = [ [ "\\[", "\\]" ], [ "$$", "$$" ] ]
  inline = [ [ "\\(", "\\)" ] ]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 6
